apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: client
          image: pankajsherchan/multi-client
          ports:
            - containerPort: 3000
